/*
 * This file was automatically generated by EvoSuite
 * Wed May 07 08:58:24 GMT 2025
 */

package Projeto;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import Projeto.Menu;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.util.SystemInUtil;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Menu_ESTest extends Menu_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String[] stringArray0 = new String[6];
      stringArray0[0] = ".-0_{xWGt+";
      stringArray0[1] = "";
      stringArray0[2] = "CL=4)f[H4<*y%X9";
      stringArray0[3] = "Yt&}D/uIR";
      String string0 = "Pfgmw:<9lPh_{U2p";
      SystemInUtil.addInputLine(".-0_{xWGt+");
      stringArray0[4] = "Pfgmw:<9lPh_{U2p";
      String string1 = "dbYh%+>l>6y";
      stringArray0[5] = "dbYh%+>l>6y";
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(6, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      // Undeclared exception!
      try { 
        menu0.pedeDouble("dbYh%+>l>6y");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SystemInUtil.addInputLine("");
      String[] stringArray0 = new String[2];
      stringArray0[0] = "";
      stringArray0[1] = "Inserir uma dura\u00E7\u00E3o no formato horas:minutos ou horas:minutos:segundos";
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(2, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      String string0 = menu0.pedeString("dd/MM/yyyy");
      assertNotNull(string0);
      assertEquals(2, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      assertEquals("", string0);
      
      String string1 = "";
      // Undeclared exception!
      try { 
        menu0.pedeString("");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String[] stringArray0 = new String[5];
      String string0 = "";
      SystemInUtil.addInputLine("");
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "LpMs33_`%CKdx\"|";
      SystemInUtil.addInputLine("4;");
      SystemInUtil.addInputLine("ze8^29LMbHO[\"i`2_");
      stringArray0[3] = "-sIJj'Z,?8OSR$[Jp";
      stringArray0[4] = "dd/MM/yyyy";
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(5, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      // Undeclared exception!
      try { 
        menu0.pedeInt("");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String[] stringArray0 = new String[3];
      SystemInUtil.addInputLine("Inserir uma data no formato dia/m\u00EAs/ano");
      SystemInUtil.addInputLine("Inserir uma data no formato dia/m\u00EAs/ano");
      stringArray0[0] = "k6H20DNVwuVn=b";
      String string0 = "";
      stringArray0[1] = "";
      String string1 = "Inserir data e hora no formato dia/m\u00EAs/ano horas:minutos:segundos";
      stringArray0[2] = "Inserir data e hora no formato dia/m\u00EAs/ano horas:minutos:segundos";
      SystemInUtil.addInputLine("Inserir uma data no formato dia/m\u00EAs/ano");
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(3, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      String string2 = menu0.pedeString("");
      assertNotNull(string2);
      assertEquals(3, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      assertFalse(string2.equals((Object)string1));
      assertFalse(string2.equals((Object)string0));
      assertEquals("Inserir uma data no formato dia/m\u00EAs/ano", string2);
      
      // Undeclared exception!
      try { 
        menu0.runMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String[] stringArray0 = new String[6];
      stringArray0[0] = "Op\u00E7\u00E3o: ";
      String string0 = "+dYS08ax;";
      stringArray0[1] = "+dYS08ax;";
      SystemInUtil.addInputLine("u>M ls^=]@Zk[^\"yys");
      stringArray0[2] = "";
      stringArray0[3] = "";
      stringArray0[4] = "u\"{AnzDQNNpP";
      stringArray0[5] = "Inserir data e hora no formato dia/m\u00EAs/ano horas:minutos:segundos";
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(6, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      // Undeclared exception!
      try { 
        menu0.runMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      String[] stringArray0 = new String[1];
      String string0 = "-------------";
      stringArray0[0] = "-------------";
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(1, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      // Undeclared exception!
      try { 
        menu0.runMenu();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1
         //
         verifyException("java.util.Arrays$ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(0, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      // Undeclared exception!
      try { 
        menu0.runMenu();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("java.util.Arrays$ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String[] stringArray0 = new String[2];
      String string0 = "X@:G{C= p7";
      stringArray0[0] = "X@:G{C= p7";
      String string1 = "(}[";
      stringArray0[1] = "(}[";
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(2, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      // Undeclared exception!
      try { 
        menu0.runMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String[] stringArray0 = new String[2];
      String string0 = "s8;@;";
      stringArray0[0] = "s8;@;";
      String string1 = "O=l%R<5x.),9gwSA";
      stringArray0[1] = "O=l%R<5x.),9gwSA";
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(2, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      int int0 = menu0.getOpcao();
      assertEquals(2, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      assertEquals((-1), int0);
      
      String string2 = "-------------\n";
      // Undeclared exception!
      menu0.pedeTempo("s8;@;");
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(0, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      int int0 = menu0.getOpcao();
      assertEquals(0, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Menu menu0 = null;
      try {
        menu0 = new Menu((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = "a:H8{&X#$M";
      stringArray0[1] = "x?M}T6Wl@$5H0j";
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(2, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      // Undeclared exception!
      menu0.pedeData("");
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(0, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      // Undeclared exception!
      try { 
        menu0.pedeInt("dd/MM/yyyy HH:mm:ss");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String[] stringArray0 = new String[6];
      stringArray0[0] = "i{-'3B&<";
      stringArray0[1] = "";
      stringArray0[2] = "";
      stringArray0[3] = "Y!|eo6i";
      stringArray0[4] = "c~q3J";
      stringArray0[5] = "";
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(6, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      // Undeclared exception!
      menu0.pedeDataHora("$U7B_>:BYgEOSn");
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = "";
      stringArray0[1] = "";
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(2, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      // Undeclared exception!
      try { 
        menu0.pedeDouble("J?$LKae2Wo3`?;n+");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      String[] stringArray0 = new String[7];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "";
      stringArray0[3] = "w=b'7b>uQ";
      stringArray0[4] = "<Dk1th";
      stringArray0[5] = "uItRF@6*";
      stringArray0[6] = "6M9Ftyo{^MMZ'6";
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(7, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      // Undeclared exception!
      try { 
        menu0.pedeString("");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      String[] stringArray0 = new String[1];
      stringArray0[0] = "v$Kg_v+t7";
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(1, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      // Undeclared exception!
      try { 
        menu0.pedeDouble("");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(0, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      // Undeclared exception!
      try { 
        menu0.pedeString((String) null);
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SystemInUtil.addInputLine((String) null);
      SystemInUtil.addInputLine("");
      SystemInUtil.addInputLine("Op\u00E7\u00E3o ");
      String[] stringArray0 = new String[8];
      stringArray0[0] = "Op\u00E7\u00E3o ";
      stringArray0[1] = "Op\u00E7\u00E3o ";
      stringArray0[2] = "Op\u00E7\u00E3o ";
      stringArray0[3] = "Op\u00E7\u00E3o ";
      stringArray0[4] = "Op\u00E7\u00E3o ";
      stringArray0[5] = "Op\u00E7\u00E3o ";
      stringArray0[6] = "Op\u00E7\u00E3o ";
      stringArray0[7] = "Op\u00E7\u00E3o ";
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(8, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      String string0 = "";
      SystemInUtil.addInputLine("Op\u00E7\u00E3o ");
      // Undeclared exception!
      menu0.pedeDataHora("q_0}/5-");
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      String[] stringArray0 = new String[2];
      stringArray0[0] = "";
      String string0 = " ";
      stringArray0[1] = " ";
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(2, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      // Undeclared exception!
      try { 
        menu0.pedeInt(" ");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      String[] stringArray0 = new String[5];
      String string0 = "";
      stringArray0[0] = "";
      stringArray0[1] = "Cm&z/^bZ ~<";
      stringArray0[2] = "";
      stringArray0[3] = "I_i(GA7{[y";
      stringArray0[4] = "";
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(5, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      // Undeclared exception!
      menu0.pedeDataHora("");
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      String[] stringArray0 = new String[8];
      stringArray0[0] = "X9";
      stringArray0[1] = "";
      stringArray0[2] = "*2=p";
      stringArray0[3] = "";
      stringArray0[4] = "SKjm0R";
      stringArray0[6] = "~";
      stringArray0[7] = "H@P'Zn$BW5u0f?g";
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(8, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      // Undeclared exception!
      try { 
        menu0.runMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      String[] stringArray0 = new String[8];
      stringArray0[0] = "X9";
      stringArray0[1] = "";
      stringArray0[2] = "*2=p";
      stringArray0[3] = "";
      stringArray0[4] = "SKjm0R";
      stringArray0[5] = "";
      stringArray0[6] = "~";
      stringArray0[7] = "H@P'Zn$BW5u0f?g";
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(8, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      // Undeclared exception!
      try { 
        menu0.runMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      String[] stringArray0 = new String[9];
      stringArray0[0] = "";
      SystemInUtil.addInputLine("|6");
      stringArray0[1] = "=2";
      stringArray0[2] = "";
      stringArray0[3] = "1iK r";
      stringArray0[4] = "";
      stringArray0[5] = "";
      stringArray0[6] = "";
      stringArray0[7] = "";
      stringArray0[8] = "LN<#5Z,v";
      Menu menu0 = new Menu(stringArray0);
      assertNotNull(menu0);
      assertEquals(9, stringArray0.length);
      assertEquals((-1), menu0.getOpcao());
      
      // Undeclared exception!
      try { 
        menu0.pedeDouble("=2");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      String[] stringArray0 = new String[4];
      stringArray0[0] = "";
      stringArray0[1] = "";
      stringArray0[2] = "";
      stringArray0[3] = "<Q7@&?LL0[`a:'";
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      menu0.pedeTempo((String) null);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      String[] stringArray0 = new String[7];
      stringArray0[0] = "";
      stringArray0[1] = "wS4TN";
      stringArray0[2] = "";
      stringArray0[3] = "L=`/C|Q_&g.";
      stringArray0[4] = "ZWMxsgA$";
      stringArray0[5] = "";
      stringArray0[6] = "C;";
      Menu menu0 = new Menu(stringArray0);
      menu0.getOpcao();
      String string0 = "]Z9 &MWs=FHWCf}\\";
      // Undeclared exception!
      try { 
        menu0.pedeInt("");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      String[] stringArray0 = new String[2];
      String string0 = "";
      stringArray0[0] = "";
      String string1 = "*^d\\I}A=SuP";
      stringArray0[1] = "*^dI}A=SuP";
      Menu menu0 = new Menu(stringArray0);
      String string2 = "yc8;_e&^tjz64/,6Jy";
      // Undeclared exception!
      menu0.pedeData("*^dI}A=SuP");
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      String[] stringArray0 = new String[0];
      Menu menu0 = new Menu(stringArray0);
      String string0 = "";
      // Undeclared exception!
      try { 
        menu0.pedeInt("");
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Scanner", e);
      }
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      SystemInUtil.addInputLine("XxSM");
      String[] stringArray0 = new String[9];
      stringArray0[0] = "XxSM";
      stringArray0[1] = "XxSM";
      stringArray0[2] = "XxSM";
      stringArray0[3] = "XxSM";
      stringArray0[4] = "XxSM";
      stringArray0[5] = "XxSM";
      stringArray0[6] = "XxSM";
      stringArray0[7] = "XxSM";
      stringArray0[8] = "XxSM";
      Menu menu0 = new Menu(stringArray0);
      // Undeclared exception!
      try { 
        menu0.runMenu();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // No line found
         //
         verifyException("java.util.Scanner", e);
      }
  }
}
